# - Find lirc_client
# Find the native lirc_client includes and library
# This module defines
#  LIRC_CLIENT_INCLUDE_DIR, where to find lirc/lirc_client.h
#  LIRC_CLIENT_LIBRARIES, the libraries needed to use
#  LIRC_CLIENT_FOUND, If false, do not try to use lirc_client


FIND_PATH(LIRC_CLIENT_INCLUDE_DIR lirc/lirc_client.h)

FIND_LIBRARY(LIRC_CLIENT_LIBRARIES NAMES lirc_client)

IF (LIRC_CLIENT_LIBRARIES AND LIRC_CLIENT_INCLUDE_DIR)
  SET(LIRC_CLIENT_FOUND "YES")
ELSE (LIRC_CLIENT_LIBRARIES AND LIRC_CLIENT_INCLUDE_DIR)
  SET(LIRC_CLIENT_FOUND "NO")
ENDIF (LIRC_CLIENT_LIBRARIES AND LIRC_CLIENT_INCLUDE_DIR)

IF (LIRC_CLIENT_FOUND)
   IF (NOT LIRC_CLIENT_FIND_QUIETLY)
      MESSAGE(STATUS "Found LircClient: ${LIRC_CLIENT_LIBRARIES}")
   ENDIF (NOT LIRC_CLIENT_FIND_QUIETLY)
ELSE (LIRC_CLIENT_FOUND)
   IF (LIRC_CLIENT_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find lirc_client library, please configure LIRC_CLIENT_LIBRARIES and LIRC_CLIENT_INCLUDE_DIR where lirc/lirc_client.h")
   ENDIF (LIRC_CLIENT_FIND_REQUIRED)
ENDIF (LIRC_CLIENT_FOUND)

MARK_AS_ADVANCED(LIRC_CLIENT_LIBRARIES LIRC_CLIENT_INCLUDE_DIR)