# FindFastoTvProtocol.cmake - Try to find the player library
# Once done this will define
#
#  FASTOTV_PROTOCOL_FOUND - System has player
#  FASTOTV_PROTOCOL_INCLUDE_DIR - The player include directory
#  FASTOTV_PROTOCOL_LIBRARIES - The libraries needed to use player

FIND_PATH(FASTOTV_PROTOCOL_INCLUDE_DIRS NAMES fastotv/config.h
 HINTS /usr /usr/local /opt PATH_SUFFIXES include
)

FIND_LIBRARY(FASTOTV_PROTOCOL_LIBRARY NAMES fastotv_protocol
 HINTS /usr /usr/local /opt
)

SET(FASTOTV_PROTOCOL_LIBRARIES ${FASTOTV_PROTOCOL_LIBRARIES} ${FASTOTV_PROTOCOL_LIBRARY})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(fastotv_protocol DEFAULT_MSG FASTOTV_PROTOCOL_LIBRARIES FASTOTV_PROTOCOL_INCLUDE_DIRS)
MARK_AS_ADVANCED(FASTOTV_PROTOCOL_INCLUDE_DIRS FASTOTV_PROTOCOL_LIBRARIES)

