FIND_PATH(SDL2_INCLUDE_DIR SDL2/SDL.h)
IF(SDL2_INCLUDE_DIR)
  SET(SDL2_INCLUDE_DIRS ${SDL2_INCLUDE_DIR}/SDL2)
ENDIF(SDL2_INCLUDE_DIR)

FIND_LIBRARY(SDL2_LIBRARY NAMES SDL2 libSDL2)
IF(SDL2_LIBRARY)
  SET(SDL2_LIBRARIES ${SDL2_LIBRARIES} ${SDL2_LIBRARY})
ENDIF(SDL2_LIBRARY)

IF(WIN32)
  FIND_LIBRARY(SDL2_MAIN_LIBRARY NAMES SDL2main libSDL2main)
  SET(SDL2_LIBRARIES ${SDL2_MAIN_LIBRARY} ${SDL2_LIBRARIES})
ENDIF(WIN32)

# ttf
FIND_PATH(SDL2_TTF_INCLUDE_DIR SDL2/SDL_ttf.h)
IF(SDL2_TTF_INCLUDE_DIR)
  SET(SDL2_INCLUDE_DIRS ${SDL2_INCLUDE_DIRS} ${SDL2_TTF_INCLUDE_DIRS})
ENDIF(SDL2_TTF_INCLUDE_DIR)
FIND_LIBRARY(SDL2_TTF_LIBRARY NAMES SDL2_ttf)
IF(SDL2_TTF_LIBRARY)
  SET(SDL2_LIBRARIES ${SDL2_LIBRARIES} ${SDL2_TTF_LIBRARY})
ENDIF(SDL2_TTF_LIBRARY)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2 REQUIRED_VARS SDL2_LIBRARIES SDL2_INCLUDE_DIRS)
MARK_AS_ADVANCED(SDL2_LIBRARY SDL2_TTF_LIBRARY SDL2_MAIN_LIBRARY SDL2_INCLUDE_DIR SDL2_TTF_INCLUDE_DIR)
